### PR TITLE
Conan recipe for Cassandra C++ driver

### PR DESCRIPTION
**Pull request by sourcedelica**
I renamed `master` to `testing/2.13.0` and created this new PR.

### Package Details
  * Package Name: **conan-cassandra**
  * Operating Systems+versions: **Linux, Windows, MinGW, macOS**
  * Compiler support: **gcc-4.9, gcc5, gcc6, gcc7, gcc8, gcc9, clang3.9, clang4.0, clang5.0, clang6.0, clang7.0, clang8, apple-clang8, apple-clang9, apple-clang9.1, apple-clang10, VS 2015, VS2017, VS2019**
  * Conan recipe repository: **https://github.com/bincrafters/conan-cassandra**

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [x] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [x] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [x] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [x] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * if not: please provide here links to your CI platforms and / or build logs and describe the problems you encounter
  * [x] I'm willing to help to maintain the recipe even after it is included into Bincrafters

Travis CI link: https://travis-ci.com/bincrafters/conan-cassandra
Appveyor link: https://ci.appveyor.com/project/sourcedelica/conan-cassandra
Bincrafters conan package link: https://bintray.com/sourcedelica/public-conan/cassandra%3Asourcedelica

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [x] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [x] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [x] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [ ] The recipe is cloned into our organisation; CI is enabled and configured and succeeds
         (Yes for Travis.  Appveyor currently testing in [sourcedelica](https://ci.appveyor.com/project/sourcedelica/conan-cassandra))
  * [x] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granting the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

### CODE REVIEW

**Comment by sourcedelica** [comment]
I'm working on the Travis issues now

**Comment by sourcedelica** [comment]
I'm testing Appveyor now: https://ci.appveyor.com/project/sourcedelica/conan-cassandra

**Comment by sourcedelica** [comment]
Re: the recipe name, how about `conan-cassandra-driver`?

**Comment by sourcedelica** [comment]
Appveyor [looks good except for VS 2019](https://ci.appveyor.com/project/sourcedelica/conan-cassandra/build/job/036fyrgsq9n3gewb) due to
```
conans.errors.ConanException: Missing prebuilt package for 'libuv/1.27.0@bincrafters/stable'
Try to build it from sources with "--build libuv"
```
VS2019 was added to conan-libuv in [this commit](https://github.com/bincrafters/conan-libuv/commit/fbf9a2bcdf8a541eee0707f5e6db1b332699daa0) but the corresponding Appveyor build was [cancelled](https://ci.appveyor.com/project/bincrafters/conan-libuv/builds/26857316) so there are no prebuilt binaries for VS 2019.

**Comment by uilianries** [comment]
@sourcedelica  Lemme check what happened with libuv first. Thanks for your effort!

**Comment by uilianries** [comment]
@sourcedelica we have a problem ... libuv requires gyp, but since that project as abandoned, Bincrafters forked it own version, but now we don't have support for MSVC 2019 (16). So we need to make a decision, move our gyp a new one which contains MSVC 2019 support, or use an alternative build tool, as cmake.

**Comment by uilianries** [comment]
I inserted cmake to build libuv on msvc16. It's a workaround.

**Comment by Croydon** [comment]
> Re: the recipe name, how about conan-cassandra-driver?

@uilianries Any opinions on how we should name this one?

I suggested that only cassandra is confusing, at it is a driver for it, not the database itself

**Comment by Croydon** [comment]
The idea with gyp was that we can migrate our gyp conan package to use one of the gyp forks. However, so far none of them is good enough maintained and the Node.js ecosystem will pretty much have a huge problem at the end of the year when they don't find a solution.... so let's wait to see what they are doing 😅

**Comment by sourcedelica** [comment]
Gracias for the merge!  Re: the recipe name, how about `conan-cassandra-driver`?

**Comment by Croydon** [comment]
@uilianries The idea was that we use some gyp fork which is getting maintained with Python 3 compatibility, but not a single fork seems to be good enough yet 

but it isn't our job to get this fixed, so I was closing our fork

**Comment by uilianries** [comment]
@Croydon In fact we need an external project, because it is not our focus, but I didn't find any cool support for msvc 16. I would love find something really useful to update our current recipe.

**Pull request merged**
